server:
  port: 8081

# logging
logging:
  level:
    root: info
    # Spring AI Advisor 패키지의 로그 레벨을 DEBUG로 설정
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG

spring:
  # .env
  config:
    import: optional:file:.env[.properties]

  application:
    name: spring-ai

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
    suffix: .html

  web:
    resources:
      static-locations: file:src/main/resources/static/

  # 파일 업로드 할 때 사이즈
  servlet:
    multipart:
      max-request-size: 20MB
      enabled: true
      max-file-size: 20MB

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  # Datasource
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user01
    password: 111111
    driver-class-name: org.postgresql.Driver

  # Chat Memory PGVector
  sql:
    init:
      mode: always
      # Manually Create Chat Memory Pgvector Table
      schema-locations:
        - "classpath:/schema/chat_pgvector.sql"

  # ai
  ai:
    # Automatically create chat memory JDBC tables
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

    # Vectorstore setting
    vectorstore:
      pgvector:
        initialize-schema: true

    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: gpt-4o
          temperature: 1.0
          max-tokens: 1000
#    openai:
#      api-key: ${GEMINI_KEY}
#      chat:
#        options:
#          model: gemini-3-flash-preview
#          temperature: 1.0
#          max-tokens: 1000
#        completions-path: /v1/chat/completions
#        base-url: https://generativelanguage.googleapis.com/v1beta/openai/
    ### MCP Setting
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json # 해당 파일의 설정으로 MCP Server 를 동작할 것이다.
        sse:
          connections:
            #### webflux 일 경우 async
            mcp-server-time-webflux:
              url: http://127.0.0.1:8089
            #### webmvc 일 경우는 sync 단 async로도 진행 가능
            mcp-server-weather-webmvc:
              url: http://127.0.0.1:8088
              sse-endpoint: /custom-sse
        # type: sync  # default sync
        type: async